spring:
  datasource:
    driver-class-name:
    username:
    password:
    url:

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  #      default_batch_fetch_size: 500